// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: scheduler.proto

package defproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scheduler API
type SchedulerTemplate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ID              *int64                 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Name            *string                `protobuf:"bytes,2,req,name=Name" json:"Name,omitempty"`
	TemplateType    *string                `protobuf:"bytes,3,req,name=TemplateType" json:"TemplateType,omitempty"`
	BaseContent     *string                `protobuf:"bytes,4,req,name=BaseContent" json:"BaseContent,omitempty"`
	MediaType       *string                `protobuf:"bytes,5,opt,name=MediaType" json:"MediaType,omitempty"`
	MediaPath       *string                `protobuf:"bytes,6,opt,name=MediaPath" json:"MediaPath,omitempty"`
	Language        *string                `protobuf:"bytes,7,req,name=Language" json:"Language,omitempty"`
	TrackingEnabled *bool                  `protobuf:"varint,8,req,name=TrackingEnabled" json:"TrackingEnabled,omitempty"`
	CreatedAt       *int64                 `protobuf:"varint,9,req,name=CreatedAt" json:"CreatedAt,omitempty"`
	UpdatedAt       *int64                 `protobuf:"varint,10,req,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SchedulerTemplate) Reset() {
	*x = SchedulerTemplate{}
	mi := &file_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerTemplate) ProtoMessage() {}

func (x *SchedulerTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerTemplate.ProtoReflect.Descriptor instead.
func (*SchedulerTemplate) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *SchedulerTemplate) GetID() int64 {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return 0
}

func (x *SchedulerTemplate) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SchedulerTemplate) GetTemplateType() string {
	if x != nil && x.TemplateType != nil {
		return *x.TemplateType
	}
	return ""
}

func (x *SchedulerTemplate) GetBaseContent() string {
	if x != nil && x.BaseContent != nil {
		return *x.BaseContent
	}
	return ""
}

func (x *SchedulerTemplate) GetMediaType() string {
	if x != nil && x.MediaType != nil {
		return *x.MediaType
	}
	return ""
}

func (x *SchedulerTemplate) GetMediaPath() string {
	if x != nil && x.MediaPath != nil {
		return *x.MediaPath
	}
	return ""
}

func (x *SchedulerTemplate) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *SchedulerTemplate) GetTrackingEnabled() bool {
	if x != nil && x.TrackingEnabled != nil {
		return *x.TrackingEnabled
	}
	return false
}

func (x *SchedulerTemplate) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *SchedulerTemplate) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

type SchedulerSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            *int64                 `protobuf:"varint,1,req,name=ID" json:"ID,omitempty"`
	Title         *string                `protobuf:"bytes,2,req,name=Title" json:"Title,omitempty"`
	TemplateID    *int64                 `protobuf:"varint,3,req,name=TemplateID" json:"TemplateID,omitempty"`
	FrequencyID   *int64                 `protobuf:"varint,4,opt,name=FrequencyID" json:"FrequencyID,omitempty"`
	GroupID       *int64                 `protobuf:"varint,5,opt,name=GroupID" json:"GroupID,omitempty"`
	ContactJID    *string                `protobuf:"bytes,6,opt,name=ContactJID" json:"ContactJID,omitempty"`
	IsActive      *bool                  `protobuf:"varint,7,req,name=IsActive" json:"IsActive,omitempty"`
	CreatedAt     *int64                 `protobuf:"varint,8,req,name=CreatedAt" json:"CreatedAt,omitempty"`
	UpdatedAt     *int64                 `protobuf:"varint,9,req,name=UpdatedAt" json:"UpdatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchedulerSchedule) Reset() {
	*x = SchedulerSchedule{}
	mi := &file_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchedulerSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchedulerSchedule) ProtoMessage() {}

func (x *SchedulerSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchedulerSchedule.ProtoReflect.Descriptor instead.
func (*SchedulerSchedule) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *SchedulerSchedule) GetID() int64 {
	if x != nil && x.ID != nil {
		return *x.ID
	}
	return 0
}

func (x *SchedulerSchedule) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *SchedulerSchedule) GetTemplateID() int64 {
	if x != nil && x.TemplateID != nil {
		return *x.TemplateID
	}
	return 0
}

func (x *SchedulerSchedule) GetFrequencyID() int64 {
	if x != nil && x.FrequencyID != nil {
		return *x.FrequencyID
	}
	return 0
}

func (x *SchedulerSchedule) GetGroupID() int64 {
	if x != nil && x.GroupID != nil {
		return *x.GroupID
	}
	return 0
}

func (x *SchedulerSchedule) GetContactJID() string {
	if x != nil && x.ContactJID != nil {
		return *x.ContactJID
	}
	return ""
}

func (x *SchedulerSchedule) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *SchedulerSchedule) GetCreatedAt() int64 {
	if x != nil && x.CreatedAt != nil {
		return *x.CreatedAt
	}
	return 0
}

func (x *SchedulerSchedule) GetUpdatedAt() int64 {
	if x != nil && x.UpdatedAt != nil {
		return *x.UpdatedAt
	}
	return 0
}

type CreateSchedulerTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *SchedulerTemplate     `protobuf:"bytes,1,req,name=Template" json:"Template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchedulerTemplateRequest) Reset() {
	*x = CreateSchedulerTemplateRequest{}
	mi := &file_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchedulerTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchedulerTemplateRequest) ProtoMessage() {}

func (x *CreateSchedulerTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchedulerTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateSchedulerTemplateRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSchedulerTemplateRequest) GetTemplate() *SchedulerTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type CreateSchedulerTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=Error" json:"Error,omitempty"`
	Template      *SchedulerTemplate     `protobuf:"bytes,2,opt,name=Template" json:"Template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchedulerTemplateResponse) Reset() {
	*x = CreateSchedulerTemplateResponse{}
	mi := &file_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchedulerTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchedulerTemplateResponse) ProtoMessage() {}

func (x *CreateSchedulerTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchedulerTemplateResponse.ProtoReflect.Descriptor instead.
func (*CreateSchedulerTemplateResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSchedulerTemplateResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *CreateSchedulerTemplateResponse) GetTemplate() *SchedulerTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type ListSchedulerTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=Error" json:"Error,omitempty"`
	Templates     []*SchedulerTemplate   `protobuf:"bytes,2,rep,name=Templates" json:"Templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulerTemplatesResponse) Reset() {
	*x = ListSchedulerTemplatesResponse{}
	mi := &file_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulerTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulerTemplatesResponse) ProtoMessage() {}

func (x *ListSchedulerTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulerTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulerTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *ListSchedulerTemplatesResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ListSchedulerTemplatesResponse) GetTemplates() []*SchedulerTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type CreateSchedulerScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *SchedulerSchedule     `protobuf:"bytes,1,req,name=Schedule" json:"Schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchedulerScheduleRequest) Reset() {
	*x = CreateSchedulerScheduleRequest{}
	mi := &file_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchedulerScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchedulerScheduleRequest) ProtoMessage() {}

func (x *CreateSchedulerScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchedulerScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateSchedulerScheduleRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSchedulerScheduleRequest) GetSchedule() *SchedulerSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type CreateSchedulerScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=Error" json:"Error,omitempty"`
	Schedule      *SchedulerSchedule     `protobuf:"bytes,2,opt,name=Schedule" json:"Schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSchedulerScheduleResponse) Reset() {
	*x = CreateSchedulerScheduleResponse{}
	mi := &file_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSchedulerScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSchedulerScheduleResponse) ProtoMessage() {}

func (x *CreateSchedulerScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSchedulerScheduleResponse.ProtoReflect.Descriptor instead.
func (*CreateSchedulerScheduleResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSchedulerScheduleResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *CreateSchedulerScheduleResponse) GetSchedule() *SchedulerSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type ListSchedulerSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *string                `protobuf:"bytes,1,opt,name=Error" json:"Error,omitempty"`
	Schedules     []*SchedulerSchedule   `protobuf:"bytes,2,rep,name=Schedules" json:"Schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulerSchedulesResponse) Reset() {
	*x = ListSchedulerSchedulesResponse{}
	mi := &file_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulerSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulerSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulerSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulerSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulerSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *ListSchedulerSchedulesResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ListSchedulerSchedulesResponse) GetSchedules() []*SchedulerSchedule {
	if x != nil {
		return x.Schedules
	}
	return nil
}

var File_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x0fscheduler.proto\x12\aneonize\"\xbb\x02\n" +
	"\x11SchedulerTemplate\x12\x0e\n" +
	"\x02ID\x18\x01 \x02(\x03R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x02(\tR\x04Name\x12\"\n" +
	"\fTemplateType\x18\x03 \x02(\tR\fTemplateType\x12 \n" +
	"\vBaseContent\x18\x04 \x02(\tR\vBaseContent\x12\x1c\n" +
	"\tMediaType\x18\x05 \x01(\tR\tMediaType\x12\x1c\n" +
	"\tMediaPath\x18\x06 \x01(\tR\tMediaPath\x12\x1a\n" +
	"\bLanguage\x18\a \x02(\tR\bLanguage\x12(\n" +
	"\x0fTrackingEnabled\x18\b \x02(\bR\x0fTrackingEnabled\x12\x1c\n" +
	"\tCreatedAt\x18\t \x02(\x03R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\n" +
	" \x02(\x03R\tUpdatedAt\"\x8d\x02\n" +
	"\x11SchedulerSchedule\x12\x0e\n" +
	"\x02ID\x18\x01 \x02(\x03R\x02ID\x12\x14\n" +
	"\x05Title\x18\x02 \x02(\tR\x05Title\x12\x1e\n" +
	"\n" +
	"TemplateID\x18\x03 \x02(\x03R\n" +
	"TemplateID\x12 \n" +
	"\vFrequencyID\x18\x04 \x01(\x03R\vFrequencyID\x12\x18\n" +
	"\aGroupID\x18\x05 \x01(\x03R\aGroupID\x12\x1e\n" +
	"\n" +
	"ContactJID\x18\x06 \x01(\tR\n" +
	"ContactJID\x12\x1a\n" +
	"\bIsActive\x18\a \x02(\bR\bIsActive\x12\x1c\n" +
	"\tCreatedAt\x18\b \x02(\x03R\tCreatedAt\x12\x1c\n" +
	"\tUpdatedAt\x18\t \x02(\x03R\tUpdatedAt\"X\n" +
	"\x1eCreateSchedulerTemplateRequest\x126\n" +
	"\bTemplate\x18\x01 \x02(\v2\x1a.neonize.SchedulerTemplateR\bTemplate\"o\n" +
	"\x1fCreateSchedulerTemplateResponse\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\x126\n" +
	"\bTemplate\x18\x02 \x01(\v2\x1a.neonize.SchedulerTemplateR\bTemplate\"p\n" +
	"\x1eListSchedulerTemplatesResponse\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\x128\n" +
	"\tTemplates\x18\x02 \x03(\v2\x1a.neonize.SchedulerTemplateR\tTemplates\"X\n" +
	"\x1eCreateSchedulerScheduleRequest\x126\n" +
	"\bSchedule\x18\x01 \x02(\v2\x1a.neonize.SchedulerScheduleR\bSchedule\"o\n" +
	"\x1fCreateSchedulerScheduleResponse\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\x126\n" +
	"\bSchedule\x18\x02 \x01(\v2\x1a.neonize.SchedulerScheduleR\bSchedule\"p\n" +
	"\x1eListSchedulerSchedulesResponse\x12\x14\n" +
	"\x05Error\x18\x01 \x01(\tR\x05Error\x128\n" +
	"\tSchedules\x18\x02 \x03(\v2\x1a.neonize.SchedulerScheduleR\tSchedulesB\fZ\n" +
	"./defproto"

var (
	file_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_proto_rawDescData []byte
)

func file_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)))
	})
	return file_scheduler_proto_rawDescData
}

var file_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_scheduler_proto_goTypes = []any{
	(*SchedulerTemplate)(nil),               // 0: neonize.SchedulerTemplate
	(*SchedulerSchedule)(nil),               // 1: neonize.SchedulerSchedule
	(*CreateSchedulerTemplateRequest)(nil),  // 2: neonize.CreateSchedulerTemplateRequest
	(*CreateSchedulerTemplateResponse)(nil), // 3: neonize.CreateSchedulerTemplateResponse
	(*ListSchedulerTemplatesResponse)(nil),  // 4: neonize.ListSchedulerTemplatesResponse
	(*CreateSchedulerScheduleRequest)(nil),  // 5: neonize.CreateSchedulerScheduleRequest
	(*CreateSchedulerScheduleResponse)(nil), // 6: neonize.CreateSchedulerScheduleResponse
	(*ListSchedulerSchedulesResponse)(nil),  // 7: neonize.ListSchedulerSchedulesResponse
}
var file_scheduler_proto_depIdxs = []int32{
	0, // 0: neonize.CreateSchedulerTemplateRequest.Template:type_name -> neonize.SchedulerTemplate
	0, // 1: neonize.CreateSchedulerTemplateResponse.Template:type_name -> neonize.SchedulerTemplate
	0, // 2: neonize.ListSchedulerTemplatesResponse.Templates:type_name -> neonize.SchedulerTemplate
	1, // 3: neonize.CreateSchedulerScheduleRequest.Schedule:type_name -> neonize.SchedulerSchedule
	1, // 4: neonize.CreateSchedulerScheduleResponse.Schedule:type_name -> neonize.SchedulerSchedule
	1, // 5: neonize.ListSchedulerSchedulesResponse.Schedules:type_name -> neonize.SchedulerSchedule
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_scheduler_proto_init() }
func file_scheduler_proto_init() {
	if File_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_proto_rawDesc), len(file_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_proto_depIdxs,
		MessageInfos:      file_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_proto = out.File
	file_scheduler_proto_goTypes = nil
	file_scheduler_proto_depIdxs = nil
}
